[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_minter = "nft_minter"
nft_swapper = "nft_swapper"
nft_project = "2nqu4HEhvXDfKGQa83Urj2Wj7EsuUcKax6tkC5YbS3bR"

[registry]
url = "https://api.apr.dev"

[workspace]
members = ["programs/*"]

[provider]
cluster = "Localnet"
wallet = '~\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
